#!/bin/bash

# Usage: ./heater-schedule <temperature in degrees Celcius, or 0 for off>

DEVICE=$(./p list | grep Photon | sed 's/^.*\[\(.*\)\].*/\1/')

TEMPERATURE=$(printf "%03d" $1)

./p function call $DEVICE muxFunction "aquariumHeaterTargetTemperature-$TEMPERATURE"
