#!/bin/bash

# Usage: ./fans-control <off|low|medium|high> <duration minutes 0-9999>

DEVICE=$(./p list | grep Photon | sed 's/^.*\[\(.*\)\].*/\1/')

if [ "$1" == "off" ]; then
  STATE=0
elif [ "$1" == "low" ]; then
  STATE=1
elif [ "$1" == "medium" ]; then
  STATE=2
elif [ "$1" == "high" ]; then
  STATE=3
else
  STATE=-1
fi

DURATION=$(printf "%04d" $2)

./p function call $DEVICE setFan "temp-$STATE:0:$DURATION"
