#!/bin/bash

# Usage: ./lights-schedule <garden|seedling|aquarium> <intensity %> <color %> <sunrise HHMM> <sunset HHMM>


DEVICE=$(./p list | grep Photon | sed 's/^.*\[\(.*\)\].*/\1/')

if [ "$1" == "garden" ]; then
  LIGHT=0
elif [ "$1" == "seedling" ]; then
  LIGHT=1
elif [ "$1" == "aquarium" ]; then
  LIGHT=2
else
  LIGHT=-1
fi

INTENSITY=$(printf "%03d" $2)
COLOR=$(printf "%03d" $3)
SUNRISE=$(printf "%04d" $4)
SUNSET=$(printf "%04d" $5)
DAYSETTINGS="$INTENSITY:$COLOR"
NIGHTSETTINGS="000:000"

echo "./p function call $DEVICE setLight \"schedule-$LIGHT:$SUNRISE:030:$SUNSET:030:$DAYSETTINGS:$NIGHTSETTINGS:2\""
./p function call $DEVICE setLight "schedule-$LIGHT:$SUNRISE:030:$SUNSET:030:$DAYSETTINGS:$NIGHTSETTINGS:2"
