#!/bin/bash

# Usage: ./lights-schedule <garden|seedling|aquarium> <intensity %> <color %> <sunrise HHMM> <sunrise duration in mins> <sunset HHMM> <sunset duration in mins>


DEVICE=$(./p list | grep Photon | sed 's/^.*\[\(.*\)\].*/\1/')

if [ "$1" == "garden" ]; then
  LIGHT=0
elif [ "$1" == "seedling" ]; then
  LIGHT=1
elif [ "$1" == "aquarium" ]; then
  LIGHT=2
else
  LIGHT=-1
fi

# Remove leading 0s from time so they are not treated as octal
sunrise="$(echo $4 | sed 's/^0*//')"
sunset="$(echo $6 | sed 's/^0*//')"

# Convert times to seconds-after-midnight
sunrise_seconds="$(( ($sunrise / 100 * 60 ) + ( $sunrise % 100) ))"
sunset_seconds="$(( ($sunset / 100 * 60 ) + ( $sunset % 100) ))"

INTENSITY=$(printf "%03d" $2)
COLOR=$(printf "%03d" $3)
SUNRISE=$(printf "%04d" $sunrise_seconds)
SUNRISE_DURATION=$(printf "%03d" $5)
SUNSET=$(printf "%04d" $sunset_seconds)
SUNSET_DURATION=$(printf "%03d" $7)
DAYSETTINGS="$INTENSITY:$COLOR"
NIGHTSETTINGS="000:$COLOR"

./p function call $DEVICE setLight "schedule-$LIGHT:$SUNRISE:$SUNRISE_DURATION:$SUNSET:$SUNSET_DURATION:$DAYSETTINGS:$NIGHTSETTINGS:2"
